---
title: "On the Ethics of Data Collection, Analysis, and Modelling in UK Benefit Fraud Prevention"
subtitle: "UCL Statistical Design and Data Ethics (Spring 2025)"
author: "[J. Tang](mailto:jinzhou.tang.22@ucl.ac.uk)"
format:
  pdf:
    number-sections: true
    code-line-numbers: true
---

## Background

In the UK, housing benefit can help you pay your rent if you are unemployed or on a low income. If you receive benefit, then you need to report a change of circumstances[^1] for you and anyone else in your house. Examples of housing benefit fraud are not reporting all income or not reporting a change of income.

In a large city in the UK, the manager who deals with housing benefit in the city wants to use data science to help identity fraud. The manager’s idea is to use data from past receivers of housing benefit who were investigated for fraud. Assume that for these people individual information is available on whether or not fraud was detected. The manager envisages using the data to define a statistical prediction model and next to use this model to identify current receivers of housing benefit who are likely to commit fraud.

You are asked to lead this project. The main statistical parts of the project are: collecting relevant data, data analysis, defining a model that can be used for prediction, and using the model to make a prediction for current receivers of housing benefit. Assume that the chosen prediction model is a logistic regression model for a binary response variable with value $1$ for fraud and value $0$ otherwise.

We will discuss the moral dimensions in data collection, analysis, and algorithmic decision-making based on prediction models in the detection and prevention of benefit fraud. We will discuss the importance of observing and implementing GDPR in this project.

In the UK, data protection is governed by the UK General Data Protection Regulation[^2] (UK GDPR) and the Data Protection Act 2018[^3].

KEY WORDS: data subject, model subject, fairness, transparency, GDPR, personal data.


## Data Collection

Regarding data consent, the data subject have the right to know if any personal data is being collected, and have the right to reject our data collection. The data subject have the right to know how their personal data will be used. The scope of use of personal data should be set out and defined prior to approval. The data subject have the right to know to what end and purposes their data are being used. Data collection is subject to data protection regulations.

## Data Analysis

Responsible and cautious practice of data analysis: Simpsons Paradox.

## On the Use of Predictive Modelling

Logistic regression produces a binary result. This makes it more prone to being biased towards/against an applicant based on their household status (e.g. single or married), racial demographics, home address (e.g. certain region(s) subject to higher fraud rate), immigration or residency status (e.g. refugees) and etc. A score, by contrast, would be more preferable. At least it allows to some extent wiggle room for local councils to closer examine applicants with high "fraud risk" as assessed by the prediction model, instead of an outright rejection.

## Appendix: Declaration

**Use of AI tools.** ChatGPT is used for learning the UK GDPR, the Data Protection Act 2018 and other cited documents and for proofreading this report.

[^1]: GOV.UK. (n.d.). Housing Benefit: Report a change of circumstances. <https://www.gov.uk/housing-benefit/report-a-change-of-circumstances>.
[^2]: European Parliament. (2016). *Regulation (EU) 2016/679 of the European Parliament and of the Council*. <https://www.legislation.gov.uk/eur/2016/679/contents>.
[^3]: UK Parliament. (2018). *Data Protection Act 2018*. <https://www.legislation.gov.uk/ukpga/2018/12/contents/enacted>.
